version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: cimg/node:current-browsers

    steps:
      - checkout
      - run:
          name: Install firebase
          command: curl -sL firebase.tools | bash
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: "Lint"
          command: pnpm run lint
      - run:
          name: "Check code format"
          command: pnpm run check-format                  
      - run:
          name: "Test"
          command: pnpm run test
      - run:
          name: "Build"
          command: pnpm run clean && pnpm run build
              
